name: flutter_spinning_wheel
description: A customizable widget to use as a spinning wheel in Flutter.
version: 1.1.0
author: David Anaya <danaya@gmail.com>
homepage: https://github.com/davidanaya/flutter-spinning-wheel
repository: https://github.com/davidanaya/flutter-spinning-wheel
issue_tracker: https://github.com/davidanaya/flutter-spinning-wheel/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/wheel-6-300.png
    - assets/images/roulette-8-300.png
    - assets/images/roulette-center-300.png